import asyncio
from typing import Protocol


class ClientsRepoProtocol(Protocol):
    def __len__(self) -> int: ...

    def has_client(self, sid: str) -> bool: ...

    def add_client(self, sid: str) -> None: ...

    def get_client(self, sid: str) -> asyncio.Queue: ...

    def remove_client(self, sid: str) -> None: ...
